apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  type: NodePort
  selector:
    app: flaskapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007  # Exposes the app on port 30007 of your machine
